config/routes.rb
Rails.application.routes.draw do
  resources :rooms
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/room.rb
class Room < ApplicationRecord

# 新しく入れた部分
def self.room_value(params)
  require 'net/http'
  require 'uri'
  require 'json'

  # uri = URI.parse('http://localhost:8080/predict?room_type=50&num_rooms=1&square=62.30&floor=3&building_type=10&structure_type=40&floor_height=8')
  uri = URI.parse("http://localhost:8080/predict?room_type=#{params[:room_type]}&num_rooms=#{params[:num_rooms]}&square=#{params[:square]}&floor=#{params[:floor]}&building_type=#{params[:building_type]}&structure_type=#{params[:structure_type]}&floor_height=#{params[:floor_height]}")
  json = Net::HTTP.get(uri)
  p json
  result = JSON.parse(json)
  p result
  return result
end
# ここまで新しく入れたもの

end

# 参考
#{params[:room_type]}
#{params[:num_rooms]}
#{params[:square]}
#{params[:floor]}
#{params[:building_type]}
#{params[:structure_type]}
#{params[:floor_height]}

#[:id]

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)
    # 追加場所
    @hama = Room.room_value(room_params)
    @room.value = @hama['result']
    # 追加場所
    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
#        @room_value
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end

# ここにPythonの回答を入れたい
#  @room_value

  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:room_type, :num_rooms, :square, :floor, :building_type, :structure_type, :floor_height)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>お部屋の価格査定ツール</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rooms/_form.html.erb
<%= form_for(room) do |f| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :room_type %>
    <%= f.number_field :room_type %>
  </div>

  <div class="field">
    <%= f.label :num_rooms %>
    <%= f.number_field :num_rooms %>
  </div>

  <div class="field">
    <%= f.label :square %>
    <%= f.number_field :square %>
  </div>

  <div class="field">
    <%= f.label :floor %>
    <%= f.number_field :floor %>
  </div>

  <div class="field">
    <%= f.label :building_type %>
    <%= f.number_field :building_type %>
  </div>

  <div class="field">
    <%= f.label :structure_type %>
    <%= f.number_field :structure_type %>
  </div>

  <div class="field">
    <%= f.label :floor_height %>
    <%= f.number_field :floor_height %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Room type</th>
      <th>Num rooms</th>
      <th>Square</th>
      <th>Floor</th>
      <th>Building type</th>
      <th>Structure type</th>
      <th>Floor height</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.room_type %></td>
        <td><%= room.num_rooms %></td>
        <td><%= room.square %></td>
        <td><%= room.floor %></td>
        <td><%= room.building_type %></td>
        <td><%= room.structure_type %></td>
        <td><%= room.floor_height %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Room type:</strong>
  <%= @room.room_type %>
</p>

<p>
  <strong>Num rooms:</strong>
  <%= @room.num_rooms %>
</p>

<p>
  <strong>Square:</strong>
  <%= @room.square %>
</p>

<p>
  <strong>Floor:</strong>
  <%= @room.floor %>
</p>

<p>
  <strong>Building type:</strong>
  <%= @room.building_type %>
</p>

<p>
  <strong>Structure type:</strong>
  <%= @room.structure_type %>
</p>

<p>
  <strong>Floor height:</strong>
  <%= @room.floor_height %>
</p>

<p>
  <strong>査定結果</strong>
  <%= @room.value %>
</p>


<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>